name: Build check for vcpkg issue

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

  pull_request:
    branches:
      - "*"

jobs:
  windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout Test Project
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Checkout vcpkg
        uses: actions/checkout@v4
        with:
          repository: 'microsoft/vcpkg'
          path: vcpkg
          submodules: 'recursive'

      - name: Build
        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
          VCPKG_INSTALLATION_ROOT: "${{ github.workspace }}/vcpkg"
        run: |
          "${{ github.workspace }}/vcpkg/bootstrap-vcpkg.bat"
          cmake --preset "Windows x64" -S "${{ github.workspace }}"
          cmake --build --preset "Windows Debug"

  linux-debug:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - name: Install Build Dependencies
        run: |
          sudo apt update
          sudo apt install build-essential ninja-build

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout Test Project
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Checkout vcpkg
        uses: actions/checkout@v4
        with:
          repository: 'microsoft/vcpkg'
          path: vcpkg
          submodules: 'recursive'

      - name: Build
        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
          VCPKG_INSTALLATION_ROOT: "${{ github.workspace }}/vcpkg"
        run: |
          "${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh"
          cmake --preset "Linux x64" -S "${{ github.workspace }}"
          cmake --build --preset "Linux Debug"
